### ISSUE TITLE
Render Output Module

### ISSUE THREAD

**Issue by sandio** [WeAreAthlon/silla.io#35]
Core module for rendering output consisting of:
- Adapters
  - [x] Smarty
  - [ ] JSON
- [x] Caching support

**Comment by pnikolov** [comment]
@kmotsov can you elaborate on the way such `JSON` adapter should render? Can you illustrate with a code a sample usage of the Adapter?

**Comment by ghost** [comment]
According to me for now it should be a pretty simple adapter. 

Some general behaviour as I see it: 
- If output is set explicitly the adapter should not make any changes to it.
- Otherwise the adapter should work exactly as a smarty adapter
  - Render the corresponding view with `json.tpl` extension
  - All assigned variables in the action should be available in the view
  - A smarty helper function will be created, that should be able to support the following usages: 
    
    ```
    {if $params.orders eq true}
        {json from = $customers, fields = ['id', 'name'], item = customer}
            {if $item->has_orders}
                {json $item->orders, ['id', 'price']}
            {/if}
        {/json}
    {else}
         {json from = $customers, fields = ['id', 'name']}{/json}
    {/if}
    ```
- Not sure if this is possible in the current structure, but ideally  the adapter should set a response header `Content-Type` to the value of an instance variable (called for example `content_type`) of the adapter that should default to `application\json` and should be changeable in the controller's action.

**Comment by pnikolov** [comment]
Latest version includes rendering module. The JSON adapter can be dispatched to another issue.
