### ISSUE TITLE
Add CLI command for cache purge

### ISSUE THREAD

**Issue by pnikolov** [WeAreAthlon/silla.io#46]
The command can be:

``` Shell
$ silla cache-purge
```

This should delete all contents of the following directories:
- `temp/cache`
- `public/*/assets/js/`
- `public/*/assets/css/`

**Comment by sandio** [comment]
1. How is a user of the command going to distinguish between the assets' cache and the cache used to store key-value pairs?
   _Note_: If the key-value cache is using the filesystem adapter, then the above would not be a problem (key-value pairs are stored in `temp/cache`). However, if the key-value cache is any other adapter, then the semantics of the above command are not that clear, in my opinion.
2. What do you think about using a three-word commands `silla cache purge`, instead of `silla cache-purge`? This way other commands concerning the `cache` or any other component will fit intuitively.
3. Generally, what do you think about using command flags, both with a long `--flag` and short `-f` version? This can be a separate issue of discussion.

**Comment by pnikolov** [comment]
I have not thought about the cache using different cache adapters...
You are right the `three word syntax` is better. For example:
- Purge all cache  (_by default_)

``` bash
$ silla cache purge --all
```
- Purge only assets cache

``` bash
$ silla cache purge --assets
```

etc.

**Comment by pnikolov** [comment]
@kalins can you share the latest code regarding this command?
